İş Başvuru Web Site  Uygulaması/JobListing/JobListing.UI/Controllers/JobsController.cs
using JobListing.BLL;
using JobListing.Entities;
using JobListing.UI.Models.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace JobListing.UI.Controllers
{
    public class JobsController : Controller
    {
        JobService _jobs;
        
        public JobsController()
        {
            _jobs = new JobService();
        }
        // GET: Jobs
        public ActionResult List()
        {
            var indexModel = new HomeIndexVM();
            indexModel.Jobs = _jobs.GetAll().OrderByDescending(x => x.JobId).Take(6).Select(x => new JobListVM()
            {
                JobId = x.JobId,
                Title = x.Title,
                Salary = x.SalaryMin + "-" + x.SalaryMax,
                Descripton = x.JobDescriptionBody,
                Address = x.Company.Address,
                CompanyName = x.Company.CompanyName,
                CompanyLogo = x.Company.Logo,
                JobNature = x.JobNature.ToString()
            }).ToList();
            indexModel.Categories = new ServiceBase<Category>().GetAll().ToList();
            indexModel.Cities = new ServiceBase<City>().GetAll().ToList();
            return View(indexModel);
        }
        public ActionResult CityList()
        {
            var indexModel = new HomeIndexVM();
 
                indexModel.Cities = _jobs.GetAll().GroupBy(x=>x.Company.CityId).Take(7).Select(x=> new CityListVM
                {
                    CityId = x.c
                   

                }).ToList();

          
              
           
           
            indexModel.Cities = new ServiceBase<City>().GetAll().ToList();
            return View(indexModel);
        }

        // GET: Jobs/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Jobs/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Jobs/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Jobs/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Jobs/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Jobs/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Jobs/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

İş Başvuru Web Site  Uygulaması/JobListing/JobListing.UI/Views/Shared/_JobListingLayout.cshtml
<!DOCTYPE html>
<html lang="zxx" class="no-js">
<head>
    <!-- Mobile Specific Meta -->
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Favicon-->
    <link rel="shortcut icon" href="/Content/img/fav.png">
    <!-- Author Meta -->
    <meta name="author" content="codepixer">
    <!-- Meta Description -->
    <meta name="description" content="">
    <!-- Meta Keyword -->
    <meta name="keywords" content="">
    <!-- meta character set -->
    <meta charset="UTF-8">
    <!-- Site Title -->
    <title>@ViewBag.Title</title>

    <link href="https://fonts.googleapis.com/css?family=Poppins:100,200,400,300,500,600,700" rel="stylesheet">
    <!--
    CSS
    ============================================= -->
    <link rel="stylesheet" href="/Content/css/linearicons.css">
    <link rel="stylesheet" href="/Content/css/font-awesome.min.css">
    <link rel="stylesheet" href="/Content/css/bootstrap.css">
    <link rel="stylesheet" href="/Content/css/magnific-popup.css">
    <link rel="stylesheet" href="/Content/css/nice-select.css">
    <link rel="stylesheet" href="/Content/css/animate.min.css">
    <link rel="stylesheet" href="/Content/css/owl.carousel.css">
    <link rel="stylesheet" href="/Content/css/main.css">
</head>
<body>

    <header id="header" id="home">
        <div class="container">
            <div class="row align-items-center justify-content-between d-flex">
                <div id="logo">
                    <a href="index.html"><img src="/Content/img/logo.png" alt="" title="" /></a>
                </div>
                <nav id="nav-menu-container">
                    <ul class="nav-menu">
                        <li class="menu-active"><a href="@Url.Action("Index","Home")">Home</a></li>
                        <li><a href="@Url.Action("AboutUs","Home")">About Us</a></li>
                        <li><a href="@Url.Action("List","Jobs")">Jobs</a></li>
                        <li><a href="blog-home.html">Blog</a></li>
                        <li><a href="@Url.Action("Contact","Home")">Contact</a></li>
                        @if (Request.IsAuthenticated)
                        {
                            using (Html.BeginForm("LogOff","Account",new { area = "" } ,FormMethod.Post,new { id = "myLogOut" })) {
                                @Html.AntiForgeryToken();
                            <li><a class="ticker-btn" href="@Url.Action("Index", "Home", new { area = "" })">Merhaba @Context.User.Identity.Name</a></li>
                            <li><a class="ticker-btn" href="javascript:document.getElementById('myLogOut').submit()">Logout</a></li>
                                }
                        }
                        else
                        {
                            <li><a class="ticker-btn" href="@Url.Action("Register", "Account", new { area = "" })">Signup</a></li>
                            <li><a class="ticker-btn" href="@Url.Action("Login", "Account", new { area = "" })">Login</a></li>
                        }
                    </ul>
                </nav><!-- #nav-menu-container -->
            </div>
        </div>
    </header><!-- #header -->
    @RenderBody()
    <!-- start footer Area -->
    <footer class="footer-area section-gap">
        <div class="container">
            <div class="row">
                <div class="col-lg-3  col-md-12">
                    <div class="single-footer-widget">
                        <h6>Top Products</h6>
                        <ul class="footer-nav">
                            <li><a href="#">Managed Website</a></li>
                            <li><a href="#">Manage Reputation</a></li>
                            <li><a href="#">Power Tools</a></li>
                            <li><a href="#">Marketing Service</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-lg-6  col-md-12">
                    <div class="single-footer-widget newsletter">
                        <h6>Newsletter</h6>
                        <p>You can trust us. we only send promo offers, not a single spam.</p>
                        <div id="mc_embed_signup">
                            <form target="_blank" novalidate="true" action="https://spondonit.us12.list-manage.com/subscribe/post?u=1462626880ade1ac87bd9c93a&amp;id=92a4423d01" method="get" class="form-inline">

                                <div class="form-group row" style="width: 100%">
                                    <div class="col-lg-8 col-md-12">
                                        <input name="EMAIL" placeholder="Enter Email" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter Email '" required="" type="email">
                                        <div style="position: absolute; left: -5000px;">
                                            <input name="b_36c4fd991d266f23781ded980_aefe40901a" tabindex="-1" value="" type="text">
                                        </div>
                                    </div>

                                    <div class="col-lg-4 col-md-12">
                                        <button class="nw-btn primary-btn">Subscribe<span class="lnr lnr-arrow-right"></span></button>
                                    </div>
                                </div>
                                <div class="info"></div>
                            </form>
                        </div>
                    </div>
                </div>
                <div class="col-lg-3  col-md-12">
                    <div class="single-footer-widget mail-chimp">
                        <h6 class="mb-20">Instragram Feed</h6>
                        <ul class="instafeed d-flex flex-wrap">
                            <li><img src="/Content/img/i1.jpg" alt=""></li>
                            <li><img src="/Content/img/i2.jpg" alt=""></li>
                            <li><img src="/Content/img/i3.jpg" alt=""></li>
                            <li><img src="/Content/img/i4.jpg" alt=""></li>
                            <li><img src="/Content/img/i5.jpg" alt=""></li>
                            <li><img src="/Content/img/i6.jpg" alt=""></li>
                            <li><img src="/Content/img/i7.jpg" alt=""></li>
                            <li><img src="/Content/img/i8.jpg" alt=""></li>
                        </ul>
                    </div>
                </div>
            </div>

            <div class="row footer-bottom d-flex justify-content-between">
                <p class="col-lg-8 col-sm-12 footer-text m-0 text-white">
                    <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                    Copyright &copy;
                    <script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
                    <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                </p>
                <div class="col-lg-4 col-sm-12 footer-social">
                    <a href="#"><i class="fa fa-facebook"></i></a>
                    <a href="#"><i class="fa fa-twitter"></i></a>
                    <a href="#"><i class="fa fa-dribbble"></i></a>
                    <a href="#"><i class="fa fa-behance"></i></a>
                </div>
            </div>
        </div>
    </footer>
    <!-- End footer Area -->

    <script src="/Scripts/js/vendor/jquery-2.2.4.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="/Scripts/js/vendor/bootstrap.min.js"></script>
    <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBhOdIF3Y9382fqJYt5I_sswSrEw5eihAA"></script>
    <script src="/Scripts/js/easing.min.js"></script>
    <script src="/Scripts/js/hoverIntent.js"></script>
    <script src="/Scripts/js/superfish.min.js"></script>
    <script src="/Scripts/js/jquery.ajaxchimp.min.js"></script>
    <script src="/Scripts/js/jquery.magnific-popup.min.js"></script>
    <script src="/Scripts/js/owl.carousel.min.js"></script>
    <script src="/Scripts/js/jquery.sticky.js"></script>
    <script src="/Scripts/js/jquery.nice-select.min.js"></script>
    <script src="/Scripts/js/parallax.min.js"></script>
    <script src="/Scripts/js/mail-script.js"></script>
    <script src="/Scripts/js/main.js"></script>
</body>
</html>

İş Başvuru Web Site  Uygulaması/JobListing/JobListing.UI/Views/Shared/_JobsList.cshtml
@model List<JobListing.UI.Models.ViewModels.JobListVM>
    <div class="container">
        <div class="row justify-content-center d-flex">
            <div class="col-lg-8 post-list">
                <ul class="cat-list">
                    <li><a href="#">Recent</a></li>
                    <li><a href="#">Full Time</a></li>
                    <li><a href="#">Intern</a></li>
                    <li><a href="#">part Time</a></li>
                </ul>
                @foreach (var job in Model)
                {
                    <div class="single-post d-flex flex-row">
                        <div class="thumb">
                            @{
                                string imageBase64 = Convert.ToBase64String(job.CompanyLogo);
                                string imageSrc = string.Format("data:image/gif;base64,{0}", imageBase64);
                            }

                            <img src="@imageSrc" class="rounded-circle" width="60" height="60" />
                            <ul class="tags">
                                <li>
                                    <a href="#">Art</a>
                                </li>
                                <li>
                                    <a href="#">Media</a>
                                </li>
                                <li>
                                    <a href="#">Design</a>
                                </li>
                            </ul>
                        </div>
                        <div class="details">
                            <div class="title d-flex flex-row justify-content-between">
                                <div class="titles">
                                    <a href="single.html"><h4>@job.Title</h4></a>
                                    <h6>@job.CompanyName</h6>
                                </div>
                                <ul class="btns">
                                    <li><a href="#"><span class="lnr lnr-heart"></span></a></li>
                                    <li><a href="#">Apply</a></li>
                                </ul>
                            </div>
                            <p>
                                @job.Descripton
                            </p>
                            <h5>Job Nature: @job.JobNature</h5>
                            <p class="address"><span class="lnr lnr-map"></span> @job.Address</p>
                            <p class="address"><span class="lnr lnr-database"></span> @job.Salary</p>
                        </div>
                    </div>
                }

            </div>
            <div class="col-lg-4 sidebar">
                <div class="single-slidebar">
                    <h4>Jobs by Location</h4>
                    <ul class="cat-list">
                        <li><a class="justify-content-between d-flex" href="category.html"><p>New York</p><span>37</span></a></li>
                        <li><a class="justify-content-between d-flex" href="category.html"><p>Park Montana</p><span>57</span></a></li>
                        <li><a class="justify-content-between d-flex" href="category.html"><p>Atlanta</p><span>33</span></a></li>
                        <li><a class="justify-content-between d-flex" href="category.html"><p>Arizona</p><span>36</span></a></li>
                        <li><a class="justify-content-between d-flex" href="category.html"><p>Florida</p><span>47</span></a></li>
                        <li><a class="justify-content-between d-flex" href="category.html"><p>Rocky Beach</p><span>27</span></a></li>
                        <li><a class="justify-content-between d-flex" href="category.html"><p>Chicago</p><span>17</span></a></li>
                    </ul>
                </div>

                <div class="single-slidebar">
                    <h4>Top rated job posts</h4>
                    <div class="active-relatedjob-carusel">
                        <div class="single-rated">
                            <img class="img-fluid" src="/Content/img/r1.jpg" alt="">
                            <a href="single.html"><h4>Creative Art Designer</h4></a>
                            <h6>Premium Labels Limited</h6>
                            <p>
                                Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod temporinc ididunt ut dolore magna aliqua.
                            </p>
                            <h5>Job Nature: Full time</h5>
                            <p class="address"><span class="lnr lnr-map"></span> 56/8, Panthapath Dhanmondi Dhaka</p>
                            <p class="address"><span class="lnr lnr-database"></span> 15k - 25k</p>
                            <a href="#" class="btns text-uppercase">Apply job</a>
                        </div>
                        <div class="single-rated">
                            <img class="img-fluid" src="/Content/img/r1.jpg" alt="">
                            <a href="single.html"><h4>Creative Art Designer</h4></a>
                            <h6>Premium Labels Limited</h6>
                            <p>
                                Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod temporinc ididunt ut dolore magna aliqua.
                            </p>
                            <h5>Job Nature: Full time</h5>
                            <p class="address"><span class="lnr lnr-map"></span> 56/8, Panthapath Dhanmondi Dhaka</p>
                            <p class="address"><span class="lnr lnr-database"></span> 15k - 25k</p>
                            <a href="#" class="btns text-uppercase">Apply job</a>
                        </div>
                        <div class="single-rated">
                            <img class="img-fluid" src="/Content/img/r1.jpg" alt="">
                            <a href="single.html"><h4>Creative Art Designer</h4></a>
                            <h6>Premium Labels Limited</h6>
                            <p>
                                Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod temporinc ididunt ut dolore magna aliqua.
                            </p>
                            <h5>Job Nature: Full time</h5>
                            <p class="address"><span class="lnr lnr-map"></span> 56/8, Panthapath Dhanmondi Dhaka</p>
                            <p class="address"><span class="lnr lnr-database"></span> 15k - 25k</p>
                            <a href="#" class="btns text-uppercase">Apply job</a>
                        </div>
                    </div>
                </div>

                <div class="single-slidebar">
                    <h4>Jobs by Category</h4>
                    <ul class="cat-list">
                        <li><a class="justify-content-between d-flex" href="category.html"><p>Technology</p><span>37</span></a></li>
                        <li><a class="justify-content-between d-flex" href="category.html"><p>Media & News</p><span>57</span></a></li>
                        <li><a class="justify-content-between d-flex" href="category.html"><p>Goverment</p><span>33</span></a></li>
                        <li><a class="justify-content-between d-flex" href="category.html"><p>Medical</p><span>36</span></a></li>
                        <li><a class="justify-content-between d-flex" href="category.html"><p>Restaurants</p><span>47</span></a></li>
                        <li><a class="justify-content-between d-flex" href="category.html"><p>Developer</p><span>27</span></a></li>
                        <li><a class="justify-content-between d-flex" href="category.html"><p>Accounting</p><span>17</span></a></li>
                    </ul>
                </div>

                <div class="single-slidebar">
                    <h4>Carrer Advice Blog</h4>
                    <div class="blog-list">
                        <div class="single-blog " style="background:#000 url(img/blog1.jpg);">
                            <a href="single.html">
                                <h4>
                                    Home Audio Recording <br>
                                    For Everyone
                                </h4>
                            </a>
                            <div class="meta justify-content-between d-flex">
                                <p>
                                    02 Hours ago
                                </p>
                                <p>
                                    <span class="lnr lnr-heart"></span>
                                    06
                                    <span class="lnr lnr-bubble"></span>
                                    02
                                </p>
                            </div>
                        </div>
                        <div class="single-blog " style="background:#000 url(img/blog2.jpg);">
                            <a href="single.html">
                                <h4>
                                    Home Audio Recording <br>
                                    For Everyone
                                </h4>
                            </a>
                            <div class="meta justify-content-between d-flex">
                                <p>
                                    02 Hours ago
                                </p>
                                <p>
                                    <span class="lnr lnr-heart"></span>
                                    06
                                    <span class="lnr lnr-bubble"></span>
                                    02
                                </p>
                            </div>
                        </div>
                        <div class="single-blog " style="background:#000 url(img/blog1.jpg);">
                            <a href="single.html">
                                <h4>
                                    Home Audio Recording <br>
                                    For Everyone
                                </h4>
                            </a>
                            <div class="meta justify-content-between d-flex">
                                <p>
                                    02 Hours ago
                                </p>
                                <p>
                                    <span class="lnr lnr-heart"></span>
                                    06
                                    <span class="lnr lnr-bubble"></span>
                                    02
                                </p>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>

İş Başvuru Web Site  Uygulaması/JobListing/JobListing.UI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>