İş Başvuru Web Site  Uygulaması/JobListing/JobListing.UI/Areas/ManagementPanel/Controllers/CompanyController.cs
using JobListing.BLL;
using JobListing.Entities;
using JobListing.UI.Areas.ManagementPanel.ViewModels;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace JobListing.UI.Areas.ManagementPanel.Controllers
{
    [Authorize(Roles ="SiteAdmin")]
    public class CompanyController : Controller
    {
        private CompanyService _companies;
        public CompanyController()
        {
            _companies = new CompanyService();
        }
        // GET: ManagementPanel/Company
        public ActionResult Index()
        {
            var cities = new ServiceBase<City>().GetAll().ToList();
            var model = _companies.GetAll().Select(x => new CompanyListVM() {
                CompanyId = x.CompanyId,
                CompanyName = x.CompanyName,
                CityId = x.CityId,
                Logo = x.Logo
            }).ToList();
            foreach (var item in model)
            {
                item.CityName = cities.SingleOrDefault(x => x.CityId == item.CityId).CityName;
            }
            return View(model);
        }

        // GET: ManagementPanel/Company/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: ManagementPanel/Company/Create
        public ActionResult Create()
        {
            ViewData["CityList"] = new ServiceBase<City>().GetAll().ToList();
            return View();
        }

        // POST: ManagementPanel/Company/Create
        [HttpPost]
        public ActionResult Create(Company company)
        {
            try
            {
                if (Request.Files.Count > 0 && Request.Files["CompanyLogo"].ContentLength > 0)
                {
                    MemoryStream target = new MemoryStream();
                    Request.Files["CompanyLogo"].InputStream.CopyTo(target);
                    company.Logo = target.ToArray();
                }
                _companies.Insert(company);

                return RedirectToAction("Index");
            }
            catch
            {
                return View(company);
            }
        }

        // GET: ManagementPanel/Company/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: ManagementPanel/Company/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: ManagementPanel/Company/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: ManagementPanel/Company/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

İş Başvuru Web Site  Uygulaması/JobListing/JobListing.UI/Areas/ManagementPanel/Views/Company/Create.cshtml
@model JobListing.Entities.Company

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/ManagementPanel/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm("Create","Company",FormMethod.Post,new { enctype ="multipart/form-data"}))
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Company</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.CompanyName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.CompanyName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.CompanyName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.CityId, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.CityId,new SelectList(ViewData["CityList"]as List<JobListing.Entities.City> ,"CityId","CityName"), new { @class = "form-control" } )
            @Html.ValidationMessageFor(model => model.CityId, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.Label("CompanyLogo", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <input name="CompanyLogo" type="file" class="form-control-file" />
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

İş Başvuru Web Site  Uygulaması/JobListing/JobListing.UI/Areas/ManagementPanel/Views/Company/Index.cshtml
@model IEnumerable<JobListing.UI.Areas.ManagementPanel.ViewModels.CompanyListVM>

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/ManagementPanel/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Logo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CompanyName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CityName)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Logo);
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CompanyName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CityName)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new {  id=item.CompanyId }) |
            @Html.ActionLink("Details", "Details", new { id=item.CompanyId }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.CompanyId })
        </td>
    </tr>
}

</table>